Repository sh0ckR6/AchievementBorder, pull requests merged in 2021-08, with the labels that each got.

#8 Change Achievement Border Control System
  src/main/java/com/github/sh0ckr6/achievementborder/listeners/BorderControl.java
Labels: type: feature, priority: asap

#10 Create configuration system
  src/main/java/com/github/sh0ckr6/achievementborder/AchievementBorder.java
  src/main/java/com/github/sh0ckr6/achievementborder/listeners/BorderControl.java
  src/main/java/com/github/sh0ckr6/achievementborder/listeners/WorldSetup.java
  src/main/java/com/github/sh0ckr6/achievementborder/managers/ConfigManager.java
Labels: type: feature, priority: high

#3 Mob Control
  .gitignore
  AchievementBorder.iml
  src/main/java/com/github/sh0ckr6/achievementborder/AchievementBorder.java
  src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
Labels: type: feature, priority: medium

#22 Add new fields to Bug Report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: priority: low, type: github, status: in progress

#23 Reload configurations after setting defaults
  src/main/java/com/github/sh0ckr6/achievementborder/AchievementBorder.java
Labels: type: bug, priority: low, status: in progress

#24 Issues/11 in game config reloading
  src/main/java/com/github/sh0ckr6/achievementborder/AchievementBorder.java
  src/main/java/com/github/sh0ckr6/achievementborder/commands/BaseCommand.java
  src/main/java/com/github/sh0ckr6/achievementborder/commands/ConfigCommand.java
  src/main/java/com/github/sh0ckr6/achievementborder/listeners/BorderControl.java
  src/main/java/com/github/sh0ckr6/achievementborder/managers/ConfigManager.java
  src/main/java/com/github/sh0ckr6/achievementborder/managers/Configuration.java
Labels: type: feature, priority: medium, status: in progress

#25 Issues/15 config edit command
  src/main/java/com/github/sh0ckr6/achievementborder/commands/ConfigCommand.java
Labels: type: feature, priority: medium, status: in progress
